name: Dotnet Build
description: Builds dotnet project

inputs:
  dotnet_version:
    required: true
  nuget_packages_directory:
    required: true
  project_path:
    required: true

runs:
  using: "composite"
  steps:
    - name: checkout repository
      uses: actions/checkout@v4
      with:
        clean: true
 
    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
      env:
        dotnet_install_dir: ${{ runner.tool_cache }}\dotnet
        
    - name: Restore dependencies
      run: dotnet restore ${{ inputs.project_path }} --packages ${{ inputs.NUGET_PACKAGES_DIRECTORY }}

    - name: build
      run: dotnet build ${{ inputs.project_path }} -c release --no-restore --packages ${{ env.nuget_packages_directory }}
