name: Test
description: Builds dotnet tests project and runs tests

on:
  workflow_call:
    inputs:
      dotnet_version:
        required: true
        type: string
      project_path:
        required: true
        type: string

env:
  NUGET_PACKAGES_DIRECTORY: ..\..\_nuget\packages

jobs:
  test:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
        env:
          DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}\dotnet

      - name: Restore dependencies
        run: dotnet restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Build tests project
        run: dotnet build ${{ inputs.project_path }} --configuration Release --no-restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Test
        run: dotnet test ${{ inputs.project_path }} -c Release --no-build
