name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  NUGET_PACKAGES_DIRECTORY: ${{ github.workspace }}/../_nuget/packages
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        env:
          DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}/dotnet

      - name: Restore dependencies
        run: dotnet restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Build
        run: dotnet build --configuration Release --no-restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Run tests
        run: dotnet test --no-build
