name: Build api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
        env:
          DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}/dotnet

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Ensure nuget packages directory exists
        run: |
          $nugetPath = "${{ runner.tool_cache }}\nuget\packages"
          if (-Not (Test-Path $nugetPath)) {
              New-Item -ItemType Directory -Path $nugetPath
          }

      - name: Restore dependencies
        run: dotnet restore --packages "${{ runner.tool_cache }}\nuget\packages"

      - name: Build
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-build
