name: Build on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET 8 locally
        shell: powershell
        run: |
          # Variables
          $DotnetVersion = "8.0.100"
          $InstallDir = "$env:USERPROFILE\dotnet"

          # Download dotnet-install script
          $dotnetInstallScript = "$env:TEMP\dotnet-install.ps1"
          Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile $dotnetInstallScript

          # Install .NET 8
          & $dotnetInstallScript -Version $DotnetVersion -InstallDir $InstallDir

          # Update PATH for this workflow job
          $env:PATH = "$InstallDir;$env:PATH"

          # Verify installation
          dotnet --version

      - name: Restore dependencies
        shell: powershell
        run: dotnet restore MySolution.sln

      - name: Build
        shell: powershell
        run: dotnet build MySolution.sln --configuration Release

      - name: Run tests
        shell: powershell
        run: dotnet test MySolution.sln --no-build
