name: Test install dotnet locally

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
          
      # Ensure NuGet package cache folder exists
      - name: Ensure NuGet package folder exists
        shell: powershell
        run: |
          $nugetPath = "${{ runner.tool_cache }}\nuget\packages"
          if (-Not (Test-Path $nugetPath)) {
              New-Item -ItemType Directory -Path $nugetPath
          }

      # Cache NuGet packages
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ${{ env.tool_cache  }}\.nuget\packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}

      - name: Restore dependencies
        shell: powershell
        run: dotnet restore

      # # Step 1: Define persistent NuGet packages folder path in _tool
      # - name: Set NuGet packages folder path
        # shell: powershell
        # run: |
          # $NugetPath = Join-Path $env:RUNNER_TOOL_CACHE ".nuget\packages"
          # Write-Host "NuGet packages folder path: $NugetPath"
          # # Export to GitHub Actions environment
          # Add-Content -Path $env:GITHUB_ENV -Value "NUGET_PACKAGES_PATH=$NugetPath"

      # # Step 2: Create the folder if it doesn't exist
      # - name: Create NuGet packages folder
        # shell: powershell
        # run: |
          # if (-not (Test-Path $env:NUGET_PACKAGES_PATH)) {
              # New-Item -ItemType Directory -Path $env:NUGET_PACKAGES_PATH | Out-Null
          # }

      # Step 3: Setup .NET SDK
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
        env:
          DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}/dotnet

      - name: Restore dependencies
        shell: powershell
        run: dotnet restore

      - name: Build
        shell: powershell
        run: dotnet build --configuration Release

      - name: Run tests
        shell: powershell
        run: dotnet test --no-build
