name: Build on Self-Hosted Runner with .NET 8

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install .NET 8 locally
        shell: powershell
        run: |
          $DotnetVersion = "8.0.100"
          $InstallDir = "$env:USERPROFILE\dotnet"
          $ScriptPath = "$env:TEMP\dotnet-install.ps1"

          # Download the install script
          Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile $ScriptPath

          # Install .NET 8 locally
          & $ScriptPath -Version $DotnetVersion -InstallDir $InstallDir

          # Update PATH and DOTNET_ROOT for the rest of this step
          $env:PATH = "$InstallDir;$env:PATH"
          $env:DOTNET_ROOT = $InstallDir

          # Verify installation
          dotnet --version
          dotnet --list-sdks

      - name: Restore dependencies
        shell: powershell
        run: |
          $InstallDir = "$env:USERPROFILE\dotnet"
          $env:PATH = "$InstallDir;$env:PATH"
          $env:DOTNET_ROOT = $InstallDir

          dotnet restore

      - name: Build
        shell: powershell
        run: |
          $InstallDir = "$env:USERPROFILE\dotnet"
          $env:PATH = "$InstallDir;$env:PATH"
          $env:DOTNET_ROOT = $InstallDir

          dotnet build --configuration Release

      - name: Run tests
        shell: powershell
        run: |
          $InstallDir = "$env:USERPROFILE\dotnet"
          $env:PATH = "$InstallDir;$env:PATH"
          $env:DOTNET_ROOT = $InstallDir

          dotnet test --no-build
