name: Test install dotnet locally

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 1: Define NuGet packages folder path
      - name: Set NuGet packages folder path
        shell: powershell
        run: |
          $NugetPath = Join-Path $env:RUNNER_TEMP ".nuget\packages"
          Write-Host "NuGet packages folder path: $NugetPath"
          # Export to GitHub Actions environment
          Add-Content -Path $env:GITHUB_ENV -Value "NUGET_PACKAGES_PATH=$NugetPath"

      # Step 2: Create the folder
      - name: Create NuGet packages folder
        shell: powershell
        run: |
          if (-not (Test-Path $env:NUGET_PACKAGES_PATH)) {
              New-Item -ItemType Directory -Path $env:NUGET_PACKAGES_PATH | Out-Null
          }

      # Step 3: Setup .NET SDK
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/*.sln
        env:
          DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}/dotnet
          NUGET_PACKAGES: ${{ env.NUGET_PACKAGES_PATH }}

      - name: Verify dotnet
        run: dotnet --list-sdks
