name: Build on Self-Hosted Runner with .NET 8

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up local .NET environment
        shell: powershell
        run: |
          # Define install directory
          $InstallDir = "$env:USERPROFILE\dotnet"

          # Set DOTNET_ROOT and prepend PATH for the rest of the job
          echo "DOTNET_ROOT=$InstallDir" >> $env:GITHUB_ENV
          echo "PATH=$InstallDir;$env:PATH" >> $env:GITHUB_ENV

      - name: Install .NET 8 locally
        shell: powershell
        run: |
          $DotnetVersion = "8.0.100"
          $InstallDir = "$env:DOTNET_ROOT"
          $ScriptPath = "$env:TEMP\dotnet-install.ps1"

          # Download install script
          Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile $ScriptPath

          # Install .NET 8 locally
          & $ScriptPath -Version $DotnetVersion -InstallDir $InstallDir

          # Verify installation
          dotnet --version
          dotnet --list-sdks

      - name: Restore dependencies
        shell: powershell
        run: dotnet restore MySolution.sln

      - name: Build
        shell: powershell
        run: dotnet build MySolution.sln --configuration Release

      - name: Run tests
        shell: powershell
        run: dotnet test MySolution.sln --no-build
