name: Build api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
        env:
          DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}/dotnet

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Setup NuGet packages directory
        run: |
          $env:NUGET_PACKAGES_DIR = "${{ runner.tool_cache }}\nuget\packages"
          if (-Not (Test-Path $env:NUGET_PACKAGES_DIR)) {
              New-Item -ItemType Directory -Path $env:NUGET_PACKAGES_DIR
          }


      - name: Restore dependencies
        run: dotnet restore --packages "$env:NUGET_PACKAGES_DIR"

      - name: Build
        run: dotnet build --configuration Release --no-restore --packages "$env:NUGET_PACKAGES_DIR"

      - name: Run tests
        run: dotnet test --no-build
