name: Build on Self-Hosted Runner with .NET 8

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      # Ensure all steps use the local .NET installation
      DOTNET_ROOT: ${{ env.USERPROFILE }}\dotnet
      PATH: ${{ env.USERPROFILE }}\dotnet;${{ env.PATH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install .NET 8 locally
        shell: powershell
        run: |
          $DotnetVersion = "8.0.100"
          $InstallDir = "$env:USERPROFILE\dotnet"
          $ScriptPath = "$env:TEMP\dotnet-install.ps1"

          # Download the install script
          Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile $ScriptPath

          # Install .NET 8 locally
          & $ScriptPath -Version $DotnetVersion -InstallDir $InstallDir

          # Verify installation
          dotnet --version
          dotnet --list-sdks

      - name: Restore dependencies
        shell: powershell
        run: dotnet restore MySolution.sln

      - name: Build
        shell: powershell
        run: dotnet build MySolution.sln --configuration Release

      - name: Run tests
        shell: powershell
        run: dotnet test MySolution.sln --no-build
