name: Deploy Production

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      dotnet_version: 9.x
      project_path: ConsoleApp1\ConsoleApp1.csproj
      test_project_path: TestProject1\TestProject1.csproj

  deploy_prod1:
    uses: ./.github/workflows/_deploy.yml
    with:
      github_environment: production
      aspnetcore_environment: prod_wit
      dotnet_version: 9.x
      project_path: ConsoleApp1\ConsoleApp1.csproj
      iis_hostname: BSS-PC-75
      iis_app_pool: kfm-api
      deployment_path: C:\rehau\services\dev\REH.KFM
    needs: build

  deploy_prod2:
    uses: ./.github/workflows/_deploy.yml
    with:
      github_environment: production2
      aspnetcore_environment: prod_srem
      dotnet_version: 9.x
      project_path: ConsoleApp1\ConsoleApp1.csproj
      iis_hostname: BSS-PC-75
      iis_app_pool: kfm-api
      deployment_path: C:\rehau\services\dev\REH.KFM
    needs: build
