name: Deploy

on:
  workflow_dispatch:
    branches:
      - main   # restricts to the 'main' branch
    inputs:
      options:
        description: "Select one or more options (comma-separated if multiple)"
        required: true
        type: choice
        # choices will appear as a dropdown, but you can allow multiple comma-separated entries
        options:
          - option1
          - option2
          - option3

env:
  NUGET_PACKAGES_DIRECTORY: ${{ github.workspace }}/../../_nuget/packages
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        env:
          DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}/dotnet

      - name: Restore dependencies
        run: dotnet restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Build
        run: dotnet build --configuration Release --no-restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: IIS Deploy
        run: echo "Selected options: ${{ github.event.inputs.options }}"
