name: Deploy prod

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  DOTNET_VERSION: "9.x"
  NUGET_PACKAGES_DIRECTORY: ..\..\_nuget\packages
  PROJECT_PATH: ConsoleApp1\ConsoleApp1.csproj
  TEST_PROJECT_PATH: TestProject1\TestProject1.csproj

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
 
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet_version }}
        env:
          dotnet_install_dir: ${{ runner.tool_cache }}\dotnet

      - name: build
        run: dotnet build ${{ env.project_path }} -c release --packages ${{ env.nuget_packages_directory }}

      - name: test
        run: |
          dotnet build ${{ env.test_project_path }} -c release --packages ${{ env.nuget_packages_directory }}
          dotnet test ${{ env.test_project_path }} -c release --no-build

  # test:
    # runs-on: [self-hosted, windows]
    # needs: build

    # steps:
      # - name: Checkout repository
        # uses: actions/checkout@v4
        # with:
          # clean: true
    
      # - name: Setup dotnet
        # uses: actions/setup-dotnet@v4
        # with:
          # dotnet-version: ${{ env.DOTNET_VERSION }}
        # env:
          # DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}\dotnet

      # - name: Restore dependencies
        # run: dotnet restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      # - name: Build
        # run: dotnet build ${{ env.TEST_PROJECT }} --configuration Release --no-restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      # - name: Test
        # run: |
          # dotnet test ${{ env.TEST_PROJECT }} --configuration Release --no-build

  deploy_prod1:
    needs: build
    environment: production
    uses: ./.github/workflows/_deploy.yml
    with:
      dotnet_version: "9.x"
      project_path: ConsoleApp1\ConsoleApp1.csproj
      deployment_path: C:\rehau\services\dev\REH.KFM

  deploy_prod2:
    needs: build
    environment: production
    uses: ./.github/workflows/_deploy.yml
    with:
      dotnet_version: "9.x"
      project_path: ConsoleApp1\ConsoleApp1.csproj
      deployment_path: C:\rehau\services\dev\REH.KFM

  deploy_prod3:
    needs: build
    environment: production
    uses: ./.github/workflows/_deploy.yml
    with:
      dotnet_version: "9.x"
      project_path: ConsoleApp1\ConsoleApp1.csproj
      deployment_path: C:\rehau\services\dev\REH.KFM

  # deploy_production:
    # runs-on: [self-hosted, windows]
    # needs: build
    # environment: production
    # env:
      # DEPLOYMENT_PATH: C:\rehau\services\dev\REH.KFM

    # steps:
      # - name: Checkout repository
        # uses: actions/checkout@v4
        # with:
          # clean: true
    
      # - name: Setup dotnet
        # uses: actions/setup-dotnet@v4
        # with:
          # dotnet-version: ${{ env.DOTNET_VERSION }}
        # env:
          # DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}\dotnet

      # # - name: Restore dependencies
        # # run: dotnet restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      # - name: Build
        # run: dotnet build ${{ env.PROJECT_PATH }} -c release --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      # - name: Publish
        # run: dotnet publish "${{ env.PROJECT_PATH }}" -c release -o "${{ env.DEPLOYMENT_PATH }}" /p:EnvironmentName=$Environment --no-build