name: Deploy prod

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  DOTNET_VERSION: "9.x"
  NUGET_PACKAGES_DIRECTORY: ${{ github.workspace }}/../../_nuget/packages
  PROJECT_PATH: REH.KFM.Service/REH.KFM.Service.csproj

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        env:
          DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}/dotnet

      - name: Restore dependencies
        run: dotnet restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Test
        run: dotnet test --no-build

  deploy_production:
    runs-on: [self-hosted, windows]
    needs: build
    environment: production
    env:
      IIS_DEPLOYMENT_PATH: C:/rehau/services/dev/REH.KFM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        env:
          DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}/dotnet

      - name: Restore dependencies
        run: dotnet restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Build
        run: dotnet build --configuration Release --no-restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Test
        run: dotnet publish "REH.KFM.Service\REH.KFM.Service.csproj" -c release -o "${DeployPath}" /p:EnvironmentName=$Environment --no-build

  deploy_production2:
    runs-on: [self-hosted, windows]
    needs: build
    environment: production2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        env:
          DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}/dotnet

      - name: Restore dependencies
        run: dotnet restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Build
        run: dotnet build --configuration Release --no-restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Test
        run: dotnet test --no-build