name: Deploy dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/_build.yml
    with:
      dotnet_version: 9.x
      project_path: ConsoleApp1\ConsoleApp1.csproj
      test_project_path: TestProject1\TestProject1.csproj

  deploy_wit_dev:
    uses: ./.github/workflows/_deploy.yml
    with:
      github_environment: development
      aspnetcore_environment: Development
      dotnet_version: 9.x
      project_path: ConsoleApp1\ConsoleApp1.csproj
      iis_hostname: BSS-PC-75
      iis_app_pool: kfm-api
      deployment_path: C:\rehau\services\dev\REH.KFM
    needs: build
