name: Test

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  workflow_dispatch:
  
env:
  DOTNET_VERSION: "9.x"
  NUGET_PACKAGES_DIRECTORY: ..\..\_nuget\packages
  TEST_PROJECT: TestProject1\TestProject1.csproj

jobs:
  test:
    runs-on: [self-hosted, windows]
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        env:
          DOTNET_INSTALL_DIR: ${{ runner.tool_cache }}\dotnet

      - name: Restore dependencies
        run: dotnet restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Build
        run: dotnet build ${{ env.TEST_PROJECT }} --configuration Release --no-restore --packages ${{ env.NUGET_PACKAGES_DIRECTORY }}

      - name: Test
        run: |
          dotnet test ${{ env.TEST_PROJECT }} --configuration Release --no-build
